api:
  container_name: api
  build: ./api/
  command: npm start
  mem_limit: 300m
  memswap_limit: 1g
  ports:
    - '3000:3000'
  expose:
    - '3000'
  links:
    - db

db:
  container_name: db
  build: ./mdb/
  command: mongod
  mem_limit: 300m
  memswap_limit: 1g
  ports:
    - '27017:27017'
    - '28017:28017'
  expose:
    - '27017'
    - '28017'
  volumes:
    - /data/db
