mongodb-server:
  container_name: mongodb-server
  mem_limit: 300m
  memswap_limit: 1g
  build: .
  ports:
    - '27017:27017'
    - '28017:28017'
  expose:
    - '27017'
    - '28017'
  volumes:
    - /data/db
